apiVersion: v1
data:
  alertmanager_fallback_config.yaml: |
    receivers:
        - name: default-receiver
    route:
        receiver: default-receiver
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/component: alertmanager
    app.kubernetes.io/instance: mimir
    app.kubernetes.io/name: mimir
    app.kubernetes.io/part-of: memberlist
  name: mimir-alertmanager-fallback-config
  namespace: mimir-test
