apiVersion: v1
data:
  runtime.yaml: |2

    {}
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: mimir
    app.kubernetes.io/name: mimir
  name: mimir-runtime
  namespace: mimir-test
