apiVersion: v1
items:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    labels:
      app.kubernetes.io/instance: mimir
      app.kubernetes.io/name: mimir
    name: mimir
    namespace: mimir-test
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    labels:
      app.kubernetes.io/instance: mimir
      app.kubernetes.io/name: rollout-operator
    name: mimir-rollout-operator
    namespace: mimir-test
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: minio-sa
    namespace: mimir-test
kind: List
metadata:
