apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: efs.csi.aws.com
    volume.kubernetes.io/storage-provisioner: efs.csi.aws.com
  creationTimestamp: "2025-12-02T03:56:31Z"
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    app.kubernetes.io/component: ingester
    app.kubernetes.io/instance: mimir
    app.kubernetes.io/name: mimir
    rollout-group: ingester
    zone: zone-b
  name: storage-mimir-ingester-zone-b-0
  namespace: mimir-test
  resourceVersion: "548570738"
  uid: ee67ce43-140d-4cda-a5be-005bfe87ba32
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: efs-sc
  volumeMode: Filesystem
  volumeName: pvc-ee67ce43-140d-4cda-a5be-005bfe87ba32
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 50Gi
  phase: Bound
