apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: efs.csi.aws.com
    volume.kubernetes.io/storage-provisioner: efs.csi.aws.com
  creationTimestamp: "2025-12-02T03:56:37Z"
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    app.kubernetes.io/component: store-gateway
    app.kubernetes.io/instance: mimir
    app.kubernetes.io/name: mimir
    rollout-group: store-gateway
    zone: zone-a
  name: storage-mimir-store-gateway-zone-a-0
  namespace: mimir-test
  resourceVersion: "548570899"
  uid: 219bd1c8-ebb0-432e-a93b-e429994098c5
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: efs-sc
  volumeMode: Filesystem
  volumeName: pvc-219bd1c8-ebb0-432e-a93b-e429994098c5
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  phase: Bound
