apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: mimir-rollout-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: mimir-rollout-operator
subjects:
- kind: ServiceAccount
  name: mimir-rollout-operator
  namespace: mimir-test
