apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: mimir
    meta.helm.sh/release-namespace: mimir-test
  creationTimestamp: "2025-12-02T03:55:41Z"
  labels:
    app.kubernetes.io/component: ingester
    app.kubernetes.io/instance: mimir
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: mimir
    app.kubernetes.io/part-of: memberlist
    app.kubernetes.io/version: 2.17.0
    helm.sh/chart: mimir-distributed-5.8.0
    name: ingester-zone-c
    rollout-group: ingester
    zone: zone-c
  name: mimir-ingester-zone-c
  namespace: mimir-test
  resourceVersion: "548569635"
  uid: 9ee7e571-0bc2-4052-9b55-6660b0a37944
spec:
  clusterIP: 172.20.214.52
  clusterIPs:
  - 172.20.214.52
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http-metrics
    port: 8080
    protocol: TCP
    targetPort: http-metrics
  - name: grpc
    port: 9095
    protocol: TCP
    targetPort: grpc
  selector:
    app.kubernetes.io/component: ingester
    app.kubernetes.io/instance: mimir
    app.kubernetes.io/name: mimir
    rollout-group: ingester
    zone: zone-c
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
