apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: mimir
    meta.helm.sh/release-namespace: mimir-test
  creationTimestamp: "2025-12-02T03:55:19Z"
  labels:
    app.kubernetes.io/component: chunks-cache
    app.kubernetes.io/instance: mimir
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: mimir
    app.kubernetes.io/version: 2.17.0
    helm.sh/chart: mimir-distributed-5.8.0
  name: mimir-chunks-cache
  namespace: mimir-test
  resourceVersion: "548569219"
  uid: b196abe4-7398-4fa5-a622-82a7f9794ada
spec:
  clusterIP: None
  clusterIPs:
  - None
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: memcached-client
    port: 11211
    protocol: TCP
    targetPort: 11211
  - name: http-metrics
    port: 9150
    protocol: TCP
    targetPort: 9150
  selector:
    app.kubernetes.io/component: chunks-cache
    app.kubernetes.io/instance: mimir
    app.kubernetes.io/name: mimir
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
