apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: mimir
    meta.helm.sh/release-namespace: mimir-test
  creationTimestamp: "2025-12-02T03:55:23Z"
  labels:
    app.kubernetes.io/component: continuous-test
    app.kubernetes.io/instance: mimir
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: mimir
    app.kubernetes.io/version: 2.17.0
    helm.sh/chart: mimir-distributed-5.8.0
  name: mimir-continuous-test-headless
  namespace: mimir-test
  resourceVersion: "548569321"
  uid: b34503ca-1060-4571-8771-04b704f69e32
spec:
  clusterIP: None
  clusterIPs:
  - None
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http-metrics
    port: 8080
    protocol: TCP
    targetPort: http-metrics
  publishNotReadyAddresses: true
  selector:
    app.kubernetes.io/component: continuous-test
    app.kubernetes.io/instance: mimir
    app.kubernetes.io/name: mimir
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
