apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: mimir
    meta.helm.sh/release-namespace: mimir-test
  creationTimestamp: "2025-12-02T03:55:44Z"
  labels:
    app.kubernetes.io/component: metadata-cache
    app.kubernetes.io/instance: mimir
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: mimir
    app.kubernetes.io/version: 2.17.0
    helm.sh/chart: mimir-distributed-5.8.0
  name: mimir-metadata-cache
  namespace: mimir-test
  resourceVersion: "548569709"
  uid: ef141d46-689d-4301-9452-f65752198185
spec:
  clusterIP: None
  clusterIPs:
  - None
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: memcached-client
    port: 11211
    protocol: TCP
    targetPort: 11211
  - name: http-metrics
    port: 9150
    protocol: TCP
    targetPort: 9150
  selector:
    app.kubernetes.io/component: metadata-cache
    app.kubernetes.io/instance: mimir
    app.kubernetes.io/name: mimir
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
