apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: mimir
    meta.helm.sh/release-namespace: mimir-test
  creationTimestamp: "2025-12-02T03:55:53Z"
  labels:
    app.kubernetes.io/component: query-frontend
    app.kubernetes.io/instance: mimir
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: mimir
    app.kubernetes.io/version: 2.17.0
    helm.sh/chart: mimir-distributed-5.8.0
  name: mimir-query-frontend
  namespace: mimir-test
  resourceVersion: "548569848"
  uid: 5893bab0-88a5-4696-8528-32905f11329f
spec:
  clusterIP: 172.20.212.120
  clusterIPs:
  - 172.20.212.120
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http-metrics
    port: 8080
    protocol: TCP
    targetPort: http-metrics
  - name: grpc
    port: 9095
    protocol: TCP
    targetPort: grpc
  selector:
    app.kubernetes.io/component: query-frontend
    app.kubernetes.io/instance: mimir
    app.kubernetes.io/name: mimir
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
