apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: mimir
    meta.helm.sh/release-namespace: mimir-test
  creationTimestamp: "2025-12-02T03:55:15Z"
  labels:
    app.kubernetes.io/component: alertmanager
    app.kubernetes.io/instance: mimir
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: mimir
    app.kubernetes.io/part-of: memberlist
    app.kubernetes.io/version: 2.17.0
    helm.sh/chart: mimir-distributed-5.8.0
    prometheus.io/service-monitor: "false"
  name: mimir-alertmanager-headless
  namespace: mimir-test
  resourceVersion: "548569145"
  uid: d4953812-1e74-4f54-883b-10b08a91faf2
spec:
  clusterIP: None
  clusterIPs:
  - None
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http-metrics
    port: 8080
    protocol: TCP
    targetPort: http-metrics
  - name: grpc
    port: 9095
    protocol: TCP
    targetPort: grpc
  - name: cluster
    port: 9094
    protocol: TCP
    targetPort: 9094
  publishNotReadyAddresses: true
  selector:
    app.kubernetes.io/component: alertmanager
    app.kubernetes.io/instance: mimir
    app.kubernetes.io/name: mimir
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
