apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: mimir
    meta.helm.sh/release-namespace: mimir-test
  creationTimestamp: "2025-12-02T03:56:00Z"
  labels:
    app.kubernetes.io/component: results-cache
    app.kubernetes.io/instance: mimir
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: mimir
    app.kubernetes.io/version: 2.17.0
    helm.sh/chart: mimir-distributed-5.8.0
  name: mimir-results-cache
  namespace: mimir-test
  resourceVersion: "548569937"
  uid: 23e61101-2c5c-43f0-8aae-310195604872
spec:
  clusterIP: None
  clusterIPs:
  - None
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: memcached-client
    port: 11211
    protocol: TCP
    targetPort: 11211
  - name: http-metrics
    port: 9150
    protocol: TCP
    targetPort: 9150
  selector:
    app.kubernetes.io/component: results-cache
    app.kubernetes.io/instance: mimir
    app.kubernetes.io/name: mimir
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
