apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    meta.helm.sh/release-name: mimir
    meta.helm.sh/release-namespace: mimir-test
  creationTimestamp: "2025-12-01T14:51:36Z"
  labels:
    app.kubernetes.io/instance: mimir
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: rollout-operator
    app.kubernetes.io/version: v0.28.0
    helm.sh/chart: rollout-operator-0.30.0
  name: mimir-rollout-operator
  namespace: mimir-test
  resourceVersion: "547917280"
  uid: 41a42c66-fcd3-4d71-a463-d67e4ca961a6
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: mimir-rollout-operator
subjects:
- kind: ServiceAccount
  name: mimir-rollout-operator
