apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    grafana.com/prepare-downscale-http-path: ingester/prepare-shutdown
    grafana.com/prepare-downscale-http-port: "8080"
    grafana.com/rollout-downscale-leader: mimir-ingester-zone-b
    meta.helm.sh/release-name: mimir
    meta.helm.sh/release-namespace: mimir-test
    rollout-max-unavailable: "50"
  creationTimestamp: "2025-12-02T03:56:32Z"
  generation: 1
  labels:
    app.kubernetes.io/component: ingester
    app.kubernetes.io/instance: mimir
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: mimir
    app.kubernetes.io/part-of: memberlist
    app.kubernetes.io/version: 2.17.0
    grafana.com/min-time-between-zones-downscale: 12h
    grafana.com/prepare-downscale: "true"
    helm.sh/chart: mimir-distributed-5.8.0
    name: ingester-zone-c
    rollout-group: ingester
    zone: zone-c
  name: mimir-ingester-zone-c
  namespace: mimir-test
  resourceVersion: "548576529"
  uid: 0cf4c1f5-49a8-488e-a9b5-28ba792a0ffc
spec:
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain
  podManagementPolicy: Parallel
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/component: ingester
      app.kubernetes.io/instance: mimir
      app.kubernetes.io/name: mimir
      rollout-group: ingester
      zone: zone-c
  serviceName: mimir-ingester-headless
  template:
    metadata:
      annotations:
        checksum/config: e3c9c077c6eea9cc262f85d8c79f1157bcee27d1e1026ee21f16495061faef1b
      creationTimestamp: null
      labels:
        app.kubernetes.io/component: ingester
        app.kubernetes.io/instance: mimir
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: mimir
        app.kubernetes.io/part-of: memberlist
        app.kubernetes.io/version: 2.17.0
        helm.sh/chart: mimir-distributed-5.8.0
        name: ingester-zone-c
        rollout-group: ingester
        zone: zone-c
      namespace: mimir-test
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: rollout-group
                operator: In
                values:
                - ingester
              - key: zone
                operator: NotIn
                values:
                - zone-c
            topologyKey: kubernetes.io/hostname
      containers:
      - args:
        - -target=ingester
        - -config.expand-env=true
        - -config.file=/etc/mimir/mimir.yaml
        - -ingester.ring.instance-availability-zone=zone-c
        - -memberlist.abort-if-fast-join-fails=true
        env:
        - name: GOMAXPROCS
          value: "4"
        image: grafana/mimir:2.17.0
        imagePullPolicy: IfNotPresent
        name: ingester
        ports:
        - containerPort: 8080
          name: http-metrics
          protocol: TCP
        - containerPort: 9095
          name: grpc
          protocol: TCP
        - containerPort: 7946
          name: memberlist
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /ready
            port: http-metrics
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            memory: 6Gi
          requests:
            cpu: 1750m
            memory: 4Gi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/mimir
          name: config
        - mountPath: /var/mimir
          name: runtime-config
        - mountPath: /data
          name: storage
        - mountPath: /active-query-tracker
          name: active-queries
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 10001
        runAsGroup: 10001
        runAsNonRoot: true
        runAsUser: 10001
        seccompProfile:
          type: RuntimeDefault
      serviceAccount: mimir
      serviceAccountName: mimir
      terminationGracePeriodSeconds: 1200
      topologySpreadConstraints:
      - labelSelector:
          matchLabels:
            app.kubernetes.io/component: ingester
            app.kubernetes.io/instance: mimir
            app.kubernetes.io/name: mimir
        maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: ScheduleAnyway
      volumes:
      - configMap:
          defaultMode: 420
          items:
          - key: mimir.yaml
            path: mimir.yaml
          name: mimir-config
        name: config
      - configMap:
          defaultMode: 420
          name: mimir-runtime
        name: runtime-config
      - emptyDir: {}
        name: active-queries
  updateStrategy:
    type: OnDelete
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      creationTimestamp: null
      name: storage
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 50Gi
      storageClassName: efs-sc
      volumeMode: Filesystem
    status:
      phase: Pending
status:
  availableReplicas: 1
  collisionCount: 0
  currentReplicas: 1
  currentRevision: mimir-ingester-zone-c-774ff7c99d
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updateRevision: mimir-ingester-zone-c-774ff7c99d
  updatedReplicas: 1
