apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    meta.helm.sh/release-name: mimir
    meta.helm.sh/release-namespace: mimir-test
  creationTimestamp: "2025-12-02T03:56:25Z"
  generation: 1
  labels:
    app.kubernetes.io/component: memcached
    app.kubernetes.io/instance: mimir
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: mimir
    app.kubernetes.io/version: 2.17.0
    helm.sh/chart: mimir-distributed-5.8.0
  name: mimir-chunks-cache
  namespace: mimir-test
  resourceVersion: "548574291"
  uid: 312805fc-4765-440a-839d-6c23ba53532f
spec:
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain
  podManagementPolicy: Parallel
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/component: chunks-cache
      app.kubernetes.io/instance: mimir
      app.kubernetes.io/name: mimir
  serviceName: mimir-chunks-cache
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/component: chunks-cache
        app.kubernetes.io/instance: mimir
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: mimir
        app.kubernetes.io/version: 2.17.0
        helm.sh/chart: mimir-distributed-5.8.0
    spec:
      containers:
      - args:
        - -m 8192
        - --extended=modern
        - -I 1m
        - -c 16384
        - -v
        - -u 11211
        image: memcached:1.6.38-alpine
        imagePullPolicy: IfNotPresent
        name: memcached
        ports:
        - containerPort: 11211
          name: client
          protocol: TCP
        resources:
          limits:
            memory: 9830Mi
          requests:
            cpu: 500m
            memory: 9830Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      - args:
        - --memcached.address=localhost:11211
        - --web.listen-address=0.0.0.0:9150
        image: prom/memcached-exporter:v0.15.3
        imagePullPolicy: IfNotPresent
        name: exporter
        ports:
        - containerPort: 9150
          name: http-metrics
          protocol: TCP
        resources:
          limits:
            memory: 250Mi
          requests:
            cpu: 50m
            memory: 50Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 10001
        runAsGroup: 10001
        runAsNonRoot: true
        runAsUser: 10001
        seccompProfile:
          type: RuntimeDefault
      serviceAccount: mimir
      serviceAccountName: mimir
      terminationGracePeriodSeconds: 30
  updateStrategy:
    type: RollingUpdate
status:
  availableReplicas: 3
  collisionCount: 0
  currentReplicas: 3
  currentRevision: mimir-chunks-cache-cbcdd5796
  observedGeneration: 1
  readyReplicas: 3
  replicas: 3
  updateRevision: mimir-chunks-cache-cbcdd5796
  updatedReplicas: 3
