apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    grafana.com/prepare-downscale-http-path: store-gateway/prepare-shutdown
    grafana.com/prepare-downscale-http-port: "8080"
    grafana.com/rollout-downscale-leader: mimir-store-gateway-zone-b
    rollout-max-unavailable: "50"
  labels:
    app.kubernetes.io/component: store-gateway
    app.kubernetes.io/instance: mimir
    app.kubernetes.io/name: mimir
    app.kubernetes.io/part-of: memberlist
    grafana.com/min-time-between-zones-downscale: 30m
    grafana.com/prepare-downscale: "true"
    name: store-gateway-zone-c
    rollout-group: store-gateway
    zone: zone-c
  name: mimir-store-gateway-zone-c
  namespace: mimir-test
spec:
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Delete  # Production: use Retain
    whenScaled: Delete   # Production: use Retain
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/component: store-gateway
      app.kubernetes.io/instance: mimir
      app.kubernetes.io/name: mimir
      rollout-group: store-gateway
      zone: zone-c
  serviceName: mimir-store-gateway-headless
  template:
    metadata:
      labels:
        app.kubernetes.io/component: store-gateway
        app.kubernetes.io/instance: mimir
        app.kubernetes.io/name: mimir
        app.kubernetes.io/part-of: memberlist
        name: store-gateway-zone-c
        rollout-group: store-gateway
        zone: zone-c
      namespace: mimir-test
    spec:
      containers:
      - args:
        - -target=store-gateway
        - -config.expand-env=true
        - -config.file=/etc/mimir/mimir.yaml
        - -store-gateway.sharding-ring.instance-availability-zone=zone-c
        - -server.grpc-max-send-msg-size-bytes=209715200
        env:
        - name: GOMAXPROCS
          value: "5"
        - name: GOMEMLIMIT
          value: "536870912"
        image: grafana/mimir:r368-547a06a0
        imagePullPolicy: IfNotPresent
        name: store-gateway
        ports:
        - containerPort: 8080
          name: http-metrics
          protocol: TCP
        - containerPort: 9095
          name: grpc
          protocol: TCP
        - containerPort: 7946
          name: memberlist
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /ready
            port: http-metrics
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          requests:
            cpu: 100m
            memory: 512Mi
        securityContext:
          allowPrivilegeEscalation: true
          capabilities: {}
          readOnlyRootFilesystem: false
          runAsUser: 0
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/mimir
          name: config
        - mountPath: /var/mimir
          name: runtime-config
        - mountPath: /data
          name: storage
        - mountPath: /active-query-tracker
          name: active-queries
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 0
        runAsGroup: 0
        runAsNonRoot: false
        runAsUser: 0
        seccompProfile:
          type: RuntimeDefault
      serviceAccount: mimir
      serviceAccountName: mimir
      terminationGracePeriodSeconds: 120
      topologySpreadConstraints:
      - labelSelector:
          matchLabels:
            app.kubernetes.io/component: store-gateway
            app.kubernetes.io/instance: mimir
            app.kubernetes.io/name: mimir
        maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: ScheduleAnyway
      volumes:
      - configMap:
          defaultMode: 420
          items:
          - key: mimir.yaml
            path: mimir.yaml
          name: mimir-config
        name: config
      - configMap:
          defaultMode: 420
          name: mimir-runtime
        name: runtime-config
      - emptyDir: {}
        name: active-queries
  updateStrategy:
    type: OnDelete
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: storage
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 2Gi
      volumeMode: Filesystem
