apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    meta.helm.sh/release-name: mimir
    meta.helm.sh/release-namespace: mimir-test
  creationTimestamp: "2025-12-02T03:56:13Z"
  generation: 1
  labels:
    app.kubernetes.io/component: continuous-test
    app.kubernetes.io/instance: mimir
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: mimir
    app.kubernetes.io/version: 2.17.0
    helm.sh/chart: mimir-distributed-5.8.0
  name: mimir-continuous-test
  namespace: mimir-test
  resourceVersion: "548570348"
  uid: f71eae90-704e-4ae4-a4f1-7bfaa9435476
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/component: continuous-test
      app.kubernetes.io/instance: mimir
      app.kubernetes.io/name: mimir
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      annotations:
        checksum/config: e3c9c077c6eea9cc262f85d8c79f1157bcee27d1e1026ee21f16495061faef1b
      creationTimestamp: null
      labels:
        app.kubernetes.io/component: continuous-test
        app.kubernetes.io/instance: mimir
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: mimir
        app.kubernetes.io/version: 2.17.0
        helm.sh/chart: mimir-distributed-5.8.0
      namespace: mimir-test
    spec:
      containers:
      - args:
        - -target=continuous-test
        - -config.expand-env=true
        - -config.file=/etc/mimir/mimir.yaml
        - -activity-tracker.filepath=
        - -server.http-listen-port=8080
        - -tests.write-read-series-test.num-series=1000
        - -tests.write-read-series-test.max-query-age=48h
        - -tests.write-endpoint=http://mimir-nginx.mimir-test.svc:80
        - -tests.read-endpoint=http://mimir-nginx.mimir-test.svc:80/prometheus
        - -tests.run-interval=5m
        - -tests.tenant-id=mimir-continuous-test
        - -log.level=info
        image: grafana/mimir:2.17.0
        imagePullPolicy: IfNotPresent
        name: continuous-test
        ports:
        - containerPort: 8080
          name: http-metrics
          protocol: TCP
        resources:
          limits:
            memory: 512Mi
          requests:
            cpu: 50m
            memory: 256Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/mimir
          name: config
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 10001
        runAsGroup: 10001
        runAsNonRoot: true
        runAsUser: 10001
        seccompProfile:
          type: RuntimeDefault
      serviceAccount: mimir
      serviceAccountName: mimir
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          items:
          - key: mimir.yaml
            path: mimir.yaml
          name: mimir-config
        name: config
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2025-12-02T03:56:13Z"
    lastUpdateTime: "2025-12-02T03:56:13Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2025-12-02T03:56:13Z"
    lastUpdateTime: "2025-12-02T03:56:20Z"
    message: ReplicaSet "mimir-continuous-test-7f5b9b8877" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
