apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    meta.helm.sh/release-name: mimir
    meta.helm.sh/release-namespace: mimir-test
  creationTimestamp: "2025-12-02T03:56:20Z"
  generation: 1
  labels:
    app.kubernetes.io/component: query-frontend
    app.kubernetes.io/instance: mimir
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: mimir
    app.kubernetes.io/version: 2.17.0
    helm.sh/chart: mimir-distributed-5.8.0
  name: mimir-query-frontend
  namespace: mimir-test
  resourceVersion: "548575363"
  uid: ea016940-05c5-43f9-aad1-bd2a9f5483d4
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/component: query-frontend
      app.kubernetes.io/instance: mimir
      app.kubernetes.io/name: mimir
  strategy:
    rollingUpdate:
      maxSurge: 15%
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        checksum/config: e3c9c077c6eea9cc262f85d8c79f1157bcee27d1e1026ee21f16495061faef1b
      creationTimestamp: null
      labels:
        app.kubernetes.io/component: query-frontend
        app.kubernetes.io/instance: mimir
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: mimir
        app.kubernetes.io/version: 2.17.0
        helm.sh/chart: mimir-distributed-5.8.0
      namespace: mimir-test
    spec:
      containers:
      - args:
        - -target=query-frontend
        - -config.expand-env=true
        - -config.file=/etc/mimir/mimir.yaml
        - -server.grpc.keepalive.max-connection-age=30s
        - -shutdown-delay=90s
        image: grafana/mimir:2.17.0
        imagePullPolicy: IfNotPresent
        name: query-frontend
        ports:
        - containerPort: 8080
          name: http-metrics
          protocol: TCP
        - containerPort: 9095
          name: grpc
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /ready
            port: http-metrics
            scheme: HTTP
          initialDelaySeconds: 45
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            memory: 1503238553600m
          requests:
            cpu: "1"
            memory: 1Gi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/mimir
          name: runtime-config
        - mountPath: /etc/mimir
          name: config
        - mountPath: /data
          name: storage
        - mountPath: /active-query-tracker
          name: active-queries
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 10001
        runAsGroup: 10001
        runAsNonRoot: true
        runAsUser: 10001
        seccompProfile:
          type: RuntimeDefault
      serviceAccount: mimir
      serviceAccountName: mimir
      terminationGracePeriodSeconds: 390
      topologySpreadConstraints:
      - labelSelector:
          matchLabels:
            app.kubernetes.io/component: query-frontend
            app.kubernetes.io/instance: mimir
            app.kubernetes.io/name: mimir
        maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: ScheduleAnyway
      volumes:
      - configMap:
          defaultMode: 420
          items:
          - key: mimir.yaml
            path: mimir.yaml
          name: mimir-config
        name: config
      - configMap:
          defaultMode: 420
          name: mimir-runtime
        name: runtime-config
      - emptyDir: {}
        name: storage
      - emptyDir: {}
        name: active-queries
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2025-12-02T03:58:38Z"
    lastUpdateTime: "2025-12-02T03:58:38Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2025-12-02T03:56:20Z"
    lastUpdateTime: "2025-12-02T03:58:38Z"
    message: ReplicaSet "mimir-query-frontend-9564f6c5" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
